#!/bin/sh

# Basically we watch only README.rst, LICENCE.rst and everything under django_structlog
sphinx-autobuild docs /docs/_build/html \
-b ${SPHINX_COMMAND} \
--port 8080 \
--host 0.0.0.0 \
--watch docs
